version: '3.7'

services:
  users:
    tty: true
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - arch-network

networks:
  arch-network:
    driver: "bridge"
    external: false